# Use an official Python base image
FROM python:3.10

# Set working directory
WORKDIR /workspace

# Upgrade pip
RUN pip install --upgrade pip

# Install required packages
RUN pip install torch==1.13.1 torchdata==0.6.0
RUN pip install transformers==4.37.0
RUN pip install datasets==2.17.0
RUN pip install evaluate==0.4.0
RUN pip install rouge_score==0.1.2
RUN pip install peft==0.3.0

# Install Jupyter Notebook
RUN pip install notebook

# Expose Jupyter notebook port
EXPOSE 8888

# Run Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
