services:
  jupyter:
    image: quay.io/jupyter/pytorch-notebook:latest
    container_name: jupyter_pytorch
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=mysecuretoken  # or use JUPYTER_PASSWORD_SHA1
    restart: unless-stopped
